import type Database from 'better-sqlite3';
import type { MessageRecord, SessionRecord } from '../sessions/session-service.js';
export class SessionRepository {
  constructor(private readonly db: Database.Database) {}
  save(session: SessionRecord) { this.db.prepare('INSERT INTO sessions (id,provider,scope,title,project_id,project_root,project_name,native_id,native_session_file,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status, title=COALESCE(excluded.title,sessions.title), project_id=excluded.project_id, project_root=excluded.project_root, project_name=excluded.project_name, native_id=excluded.native_id, native_session_file=excluded.native_session_file, updated_at=excluded.updated_at').run(session.id, session.provider, session.scope, session.title ?? null, session.projectId ?? null, session.projectRoot ?? null, session.projectName ?? null, session.nativeId ?? null, session.nativeSessionFile ?? null, session.status, session.createdAt, session.updatedAt); return session; }
  get(id: string) { return this.db.prepare('SELECT id,provider,scope,title,project_id as projectId,project_root as projectRoot,project_name as projectName,native_id as nativeId,native_session_file as nativeSessionFile,status,created_at as createdAt,updated_at as updatedAt FROM sessions WHERE id=?').get(id) as SessionRecord | undefined; }
  list() { return this.db.prepare('SELECT id,provider,scope,title,project_id as projectId,project_root as projectRoot,project_name as projectName,native_id as nativeId,native_session_file as nativeSessionFile,status,created_at as createdAt,updated_at as updatedAt FROM sessions ORDER BY updated_at DESC').all() as SessionRecord[]; }
  saveMessage(message: MessageRecord) { this.db.prepare('INSERT INTO messages (id,session_id,role,content,sequence,created_at) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET content=excluded.content, sequence=excluded.sequence').run(message.id, message.sessionId, message.role, JSON.stringify(message.content), message.sequence, message.createdAt); return message; }
  listMessages(sessionId: string) { return (this.db.prepare('SELECT id,session_id as sessionId,role,content,sequence,created_at as createdAt FROM messages WHERE session_id=? ORDER BY sequence, created_at').all(sessionId) as Array<Omit<MessageRecord, 'content'> & { content: string }>).map((message) => ({ ...message, content: JSON.parse(message.content) })); }
}
