import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { Workbench } from './workbench/Workbench.js';
import './styles.css';
import './explorer.css';
import './chat.css';
import './template-overrides.css';
import './template-fidelity.css';
import './spec-overrides.css';
createRoot(document.getElementById('root')!).render(<StrictMode><Workbench /></StrictMode>);
