import { useEffect, useRef, useState } from 'react';
import { EventSequencer } from '@codeagent-studio/protocol';
import type { AgentEvent } from '@codeagent-studio/protocol';
import { applyAgentEvent, type ChatMessage } from './chat-state.js';

type Props = { sessionId: string; providerName?: string; providers?: string[]; disabledProviders?: string[]; loadMessages?: () => Promise<ChatMessage[]>; subscribe?: (listener: (event: AgentEvent) => void) => () => void; onPrompt?: (text: string, provider: string) => Promise<void> | void; onAbort?: (sessionId: string) => Promise<unknown> | unknown; onProviderChange?: (provider: string) => void };

export function ChatPanel({ sessionId, providerName = 'Claude', providers = ['Claude', 'Cursor', 'Codex', 'Pi', 'OpenCode'], disabledProviders = [], loadMessages, subscribe, onPrompt, onAbort, onProviderChange }: Props) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [provider, setProvider] = useState(providerName);
  const [draft, setDraft] = useState('');
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string>();
  const [composerHint, setComposerHint] = useState('支持 Markdown、代码和多行输入');
  const [composerNotice, setComposerNotice] = useState('');
  const [showCommandMenu, setShowCommandMenu] = useState(false);
  const [showScrollButton, setShowScrollButton] = useState(false);
  const attachmentInput = useRef<HTMLInputElement>(null);
  const sequencer = useRef(new EventSequencer());
  const transcriptRef = useRef<HTMLDivElement>(null);
  const stickToBottom = useRef(true);
  const resizeComposer = (element: HTMLTextAreaElement) => { element.style.height = 'auto'; element.style.height = `${Math.min(element.scrollHeight, 240)}px`; };
  useEffect(() => { setProvider(providerName); }, [providerName]);
  useEffect(() => subscribe?.((event) => { if (event.sessionId === sessionId && sequencer.current.accept(event)) setMessages((current) => applyAgentEvent(current, event)); }), [sessionId, subscribe]);
  useEffect(() => { let active = true; sequencer.current = new EventSequencer(); setMessages([]); if (loadMessages && sessionId !== 'new-chat') void loadMessages().then((loaded) => { if (active) setMessages(loaded); }); return () => { active = false; }; }, [sessionId]);
  useEffect(() => { const element = transcriptRef.current; if (!element || !stickToBottom.current) return; element.scrollTop = element.scrollHeight; }, [messages]);
  const scrollToBottom = () => { const element = transcriptRef.current; if (!element) return; element.scrollTo({ top: element.scrollHeight, behavior: 'smooth' }); stickToBottom.current = true; setShowScrollButton(false); };
  const useQuickPrompt = (text: string) => { setDraft(text); setComposerNotice('已填入快捷任务，按 Enter 发送'); requestAnimationFrame(() => { const input = document.querySelector<HTMLTextAreaElement>('.chat-composer textarea'); input?.focus(); resizeComposer(input); }); };
  const send = async () => { const text = draft.trim(); if (!text || sending) return; setDraft(''); setError(undefined); setMessages((current) => [...current, { id: crypto.randomUUID(), role: 'user', content: text, status: 'done' }]); setSending(true); try { if (!onPrompt) throw new Error('Agent 接口不可用，请重启应用'); await onPrompt(text, provider); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Agent 请求失败'); } finally { setSending(false); } };
  const copyMessage = async (content: string) => { try { await navigator.clipboard?.writeText(content); } catch { /* clipboard may be unavailable in tests */ } };
  return <section className="chat-panel" aria-label="Agent 对话">
    <header className="chat-header"><div><span className="eyebrow">WORKSPACE CHAT</span><h1>{provider}</h1><span className="session-meta">会话 {sessionId}</span></div><label className="provider-picker">Agent<select aria-label="选择 Provider" value={provider} onChange={(event) => { setProvider(event.target.value); onProviderChange?.(event.target.value); }}>{providers.map((item) => <option key={item} value={item} disabled={disabledProviders.includes(item)}>{item}{disabledProviders.includes(item) ? '（未安装）' : ''}</option>)}</select></label></header>
    {error && <p className="chat-error" role="alert">{error}</p>}
    <div ref={transcriptRef} className="chat-transcript" role="log" aria-live="polite" onScroll={(event) => { const element = event.currentTarget; const atBottom = element.scrollHeight - element.scrollTop - element.clientHeight < 48; stickToBottom.current = atBottom; setShowScrollButton(!atBottom && element.scrollHeight > element.clientHeight + 80); }}>{messages.length === 0 ? <div className="chat-empty"><div className="empty-mark">✦</div><h2>今天想让 Agent 做什么？</h2><p>从一个快捷任务开始，或直接描述你的代码问题。</p><div className="quick-prompts"><button type="button" onClick={() => useQuickPrompt('帮我快速了解这个项目的目录结构和主要技术栈')}>了解项目</button><button type="button" onClick={() => useQuickPrompt('检查当前项目中最值得优先修复的问题，并给出修复计划')}>检查问题</button><button type="button" onClick={() => useQuickPrompt('帮我实现一个小功能，并先说明你准备修改哪些文件')}>实现功能</button><button type="button" onClick={() => useQuickPrompt('阅读当前代码，找出潜在的性能或安全风险')}>代码审查</button></div></div> : messages.map((message) => <article className={`chat-message chat-message-${message.role} ${message.status === 'error' ? 'is-error' : ''}`} key={message.id} data-role={message.role}><div className="message-avatar" aria-hidden="true">{message.role === 'user' ? '你' : message.role === 'tool' ? '⌘' : '✦'}</div><div className="message-body"><div className="message-heading"><strong>{message.role === 'user' ? '你' : message.role === 'tool' ? '工具调用' : provider}</strong>{message.status === 'streaming' && <span className="streaming-badge">生成中</span>}</div><p>{message.content}{message.status === 'streaming' ? <span className="cursor-block" aria-label="正在生成">▍</span> : ''}</p><div className="message-actions"><button type="button" aria-label="复制消息" onClick={() => void copyMessage(message.content)}>复制</button><button type="button" aria-label="切换 Markdown">MD</button><time>{new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div></div></article>)}</div>
    {showScrollButton && <button type="button" className="scroll-bottom" onClick={scrollToBottom}>↓ 回到底部</button>}
    <form className="chat-composer" onSubmit={(event) => { event.preventDefault(); void send(); }}><textarea aria-label="消息" placeholder="输入 / 调用命令，@ 选择文件，或向 Agent 提问…" value={draft} onFocus={() => setComposerHint('Enter 发送 · Shift + Enter 换行')} onChange={(event) => { setDraft(event.target.value); setShowCommandMenu(event.target.value.startsWith('/')); resizeComposer(event.currentTarget); }} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void send(); } }} disabled={sending} /><div className="composer-toolbar"><div className="composer-tools"><input ref={attachmentInput} type="file" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) setComposerNotice(`已选择附件：${file.name}`); event.target.value = ''; }} /><button type="button" aria-label="添加附件" className="toolbar-icon" onClick={() => attachmentInput.current?.click()}>⌕</button><button type="button" aria-label="查看 Token 统计" className="token-chip" onClick={() => setComposerNotice('Token 统计为当前草稿和会话文本的估算值。')}>⌁ <strong>{Math.max(1, Math.ceil((draft.length + messages.reduce((total, item) => total + item.content.length, 0)) / 4))}K</strong> tokens</button><button type="button" aria-label="引用文件" className="toolbar-icon" onClick={() => { setComposerNotice('请在左侧文件资源管理器点击文件，即可打开并引用。'); setDraft((current) => current || '@'); }}>▢</button></div><div className="composer-actions"><span className="composer-model" title={`当前 Agent：${provider}`}>{provider}</span>{sending ? <button type="button" className="stop-action" onClick={() => { setSending(false); void onAbort?.(sessionId); }}>停止</button> : <button type="submit" className="send-action" aria-label="发送" disabled={!draft.trim()}>➤</button>}</div></div>{showCommandMenu && <div className="command-menu" role="listbox"><button type="button" onClick={() => { setDraft('/help '); setShowCommandMenu(false); }}>/help <span>查看可用命令</span></button><button type="button" onClick={() => { setDraft('/clear '); setShowCommandMenu(false); }}>/clear <span>清空当前会话</span></button></div>}<span className="composer-hint">{composerNotice || composerHint}</span></form>
  </section>;
}
