import { MarkdownLite } from './markdown-lite.js';
import type { ChatMessage } from './chat-state.js';

type Props = { message: ChatMessage; provider: string; copied: boolean; sending: boolean; onCopy: (id: string, content: string) => void; onRegenerate: () => void; onFeedback: () => void };
export function MessageItem({ message, provider, copied, sending, onCopy, onRegenerate, onFeedback }: Props) {
  const toolParts = message.role === 'tool' ? message.content.split('\n') : [];
  const toolName = toolParts[0] || '工具调用';
  const toolDetail = toolParts.slice(1).join('\n');
  return <article className={`chat-message chat-message-${message.role} ${message.status === 'error' ? 'is-error' : ''}`} data-role={message.role}><div className="message-avatar" aria-hidden="true">{message.role === 'user' ? '你' : message.role === 'tool' ? '⌘' : '✦'}</div><div className="message-body"><div className="message-heading"><strong>{message.role === 'user' ? '你' : message.role === 'tool' ? '工具调用' : provider}</strong>{message.status === 'streaming' && <span className="streaming-badge">生成中</span>}</div>{message.role === 'tool' ? <details className="tool-call-block" open={message.status === 'streaming'}><summary><span className="tool-caret">›</span><strong>{toolName}</strong><span className={`tool-status tool-status-${message.status ?? 'done'}`}>{message.status === 'streaming' ? '执行中' : message.status === 'error' ? '失败' : '已完成'}</span></summary><pre>{toolDetail}</pre></details> : <MarkdownLite content={message.content} />}{message.status === 'streaming' && <span className="cursor-block" aria-label="正在生成">▍</span>}<div className="message-actions"><button type="button" aria-label="复制消息" onClick={() => onCopy(message.id, message.content)}>{copied ? '已复制' : '复制'}</button>{message.role === 'agent' && <><button type="button" aria-label="重新生成" onClick={onRegenerate} disabled={sending}>重新生成</button><button type="button" aria-label="赞" onClick={onFeedback}>赞</button><button type="button" aria-label="踩" onClick={onFeedback}>踩</button></>}<time>{new Date(message.createdAt ?? Date.now()).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div></div></article>;
}
